#!/usr/bin/with-contenv bash
DLIB_BRANCH=v19.19
PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib64/pkgconfig/
PDLIB_BRANCH=master
core_count=grep -c processor /proc/cpuinfo
#ALPINE_VER=$(cat /etc/apk/repositories | grep main | sed 's|.*alpine/v||' | sed 's|/main.*||')
PHP_VER=8
echo "php installed version $PHP_VER"
echo "existing cores $core_count"
echo "**** Installing required packages ****"
apk add --no-cache \
    php8-dev \
    php8-gd \
    php8-common 
    #\
    #cmake \
    #make \
    #gcc \
    #libgcc \
    #libc-dev \
    #g++ \
    #libstdc++ \
    #unzip \
    #openblas-dev \
    #libx11-dev \
    #pkgconf \
    #jpeg \
    #jpeg-dev \
    #libpng \
    #libpng-dev \
    #bzip2-dev \
    #libstdc++ \
    #openblas-dev \
    #lapack-dev 
    
#echo "@testing https://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories

echo "installing dlib"
apk add php8-pdlib --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing

echo 'memory_limit=2048M' > /etc/php8/conf.d/memory-limit.ini
echo "building libraries"

#wget -c -q https://github.com/davisking/dlib/archive/${DLIB_BRANCH}.tar.gz 
# tar xf ${DLIB_BRANCH}.tar.gz 
# mv dlib-* dlib 
# cd dlib/dlib 
# mkdir build 
# cd build 
# cmake -DBUILD_SHARED_LIBS=ON .. `-D CMAKE_BUILD_TYPE=Release`
# make -j $core_count
# make install


#pkg-config --libs --cflags libjpeg 
#pkg-config --libs --cflags dlib-1
#cd /tmp
#echo "building pdlib"
#wget -c -q https://github.com/goodspb/pdlib/archive/$PDLIB_BRANCH.zip 
# unzip $PDLIB_BRANCH 
# mv pdlib-* pdlib 
# cd pdlib 
# phpize8 
# ./configure --with-php-config=/usr/bin/php-config8 
# make -j $core_count
# make install

#echo "[pdlib]" >> /etc/php8/conf.d/pdlib.ini
echo "extension=pdlib.so" > /etc/php8/conf.d/pdlib.ini

#cd /tmp
#echo "testing models"
#wget https://github.com/matiasdelellis/facerecognition/files/3107912/crop-tests.zip 
# unzip -q crop-tests.zip 
# rm crop-tests/cropped_* 
# rm crop-tests/test.csv
#cd crop-tests ; mkdir -p vendor/models/1/
# wget https://github.com/davisking/dlib-models/raw/94cdb1e40b1c29c0bfcaf7355614bfe6da19460e/mmod_human_face_detector.dat.bz2 -O vendor/models/1/mmod_human_face_detector.dat.bz2 
# bzip2 -d vendor/models/1/mmod_human_face_detector.dat.bz2 
# wget https://github.com/davisking/dlib-models/raw/2a61575dd45d818271c085ff8cd747613a48f20d/dlib_face_recognition_resnet_model_v1.dat.bz2 -O vendor/models/1/dlib_face_recognition_resnet_model_v1.dat.bz2 
# bzip2 -d vendor/models/1/dlib_face_recognition_resnet_model_v1.dat.bz2 
# wget https://github.com/davisking/dlib-models/raw/4af9b776281dd7d6e2e30d4a2d40458b1e254e40/shape_predictor_5_face_landmarks.dat.bz2 -O vendor/models/1/shape_predictor_5_face_landmarks.dat.bz2 
# bzip2 -d vendor/models/1/shape_predictor_5_face_landmarks.dat.bz2 
 
#php8 test.php
