#!/usr/bin/with-contenv bash

echo "installing dlib"
apk add php8-pdlib --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing

echo 'memory_limit=2048M' > /etc/php8/conf.d/memory-limit.ini
echo "building libraries"
